CREATE SCHEMA BRONZE;

---------------------------
-- BRONZE
---------------------------

CREATE TABLE BRONZE.NSW_LGA_CODE_RAW (
    LGA_CODE  TEXT,
    LGA_NAME  TEXT
);

CREATE TABLE BRONZE.NSW_LGA_SUBURB_RAW (
    LGA_NAME     TEXT,
    SUBURB_NAME  TEXT
);

CREATE TABLE BRONZE.CENSUS_DATA_G01_RAW (
    LGA_CODE_2016                     TEXT,
    TOT_P_M                            TEXT,
    TOT_P_F                            TEXT,
    TOT_P_P                            TEXT,
    AGE_0_4_YR_M                       TEXT,
    AGE_0_4_YR_F                       TEXT,
    AGE_0_4_YR_P                       TEXT,
    AGE_5_14_YR_M                      TEXT,
    AGE_5_14_YR_F                      TEXT,
    AGE_5_14_YR_P                      TEXT,
    AGE_15_19_YR_M                     TEXT,
    AGE_15_19_YR_F                     TEXT,
    AGE_15_19_YR_P                     TEXT,
    AGE_20_24_YR_M                     TEXT,
    AGE_20_24_YR_F                     TEXT,
    AGE_20_24_YR_P                     TEXT,
    AGE_25_34_YR_M                     TEXT,
    AGE_25_34_YR_F                     TEXT,
    AGE_25_34_YR_P                     TEXT,
    AGE_35_44_YR_M                     TEXT,
    AGE_35_44_YR_F                     TEXT,
    AGE_35_44_YR_P                     TEXT,
    AGE_45_54_YR_M                     TEXT,
    AGE_45_54_YR_F                     TEXT,
    AGE_45_54_YR_P                     TEXT,
    AGE_55_64_YR_M                     TEXT,
    AGE_55_64_YR_F                     TEXT,
    AGE_55_64_YR_P                     TEXT,
    AGE_65_74_YR_M                     TEXT,
    AGE_65_74_YR_F                     TEXT,
    AGE_65_74_YR_P                     TEXT,
    AGE_75_84_YR_M                     TEXT,
    AGE_75_84_YR_F                     TEXT,
    AGE_75_84_YR_P                     TEXT,
    AGE_85OV_M                         TEXT,
    AGE_85OV_F                         TEXT,
    AGE_85OV_P                         TEXT,
    COUNTED_CENSUS_NIGHT_HOME_M        TEXT,
    COUNTED_CENSUS_NIGHT_HOME_F        TEXT,
    COUNTED_CENSUS_NIGHT_HOME_P        TEXT,
    COUNT_CENSUS_NT_EWHERE_AUST_M      TEXT,
    COUNT_CENSUS_NT_EWHERE_AUST_F      TEXT,
    COUNT_CENSUS_NT_EWHERE_AUST_P      TEXT,
    INDIGENOUS_PSNS_ABORIGINAL_M       TEXT,
    INDIGENOUS_PSNS_ABORIGINAL_F       TEXT,
    INDIGENOUS_PSNS_ABORIGINAL_P       TEXT,
    INDIG_PSNS_TORRES_STRAIT_IS_M      TEXT,
    INDIG_PSNS_TORRES_STRAIT_IS_F      TEXT,
    INDIG_PSNS_TORRES_STRAIT_IS_P      TEXT,
    INDIG_BTH_ABOR_TORRES_ST_IS_M      TEXT,
    INDIG_BTH_ABOR_TORRES_ST_IS_F      TEXT,
    INDIG_BTH_ABOR_TORRES_ST_IS_P      TEXT,
    INDIGENOUS_P_TOT_M                 TEXT,
    INDIGENOUS_P_TOT_F                 TEXT,
    INDIGENOUS_P_TOT_P                 TEXT,
    BIRTHPLACE_AUSTRALIA_M             TEXT,
    BIRTHPLACE_AUSTRALIA_F             TEXT,
    BIRTHPLACE_AUSTRALIA_P             TEXT,
    BIRTHPLACE_ELSEWHERE_M             TEXT,
    BIRTHPLACE_ELSEWHERE_F             TEXT,
    BIRTHPLACE_ELSEWHERE_P             TEXT,
    LANG_SPOKEN_HOME_ENG_ONLY_M        TEXT,
    LANG_SPOKEN_HOME_ENG_ONLY_F        TEXT,
    LANG_SPOKEN_HOME_ENG_ONLY_P        TEXT,
    LANG_SPOKEN_HOME_OTH_LANG_M        TEXT,
    LANG_SPOKEN_HOME_OTH_LANG_F        TEXT,
    LANG_SPOKEN_HOME_OTH_LANG_P        TEXT,
    AUSTRALIAN_CITIZEN_M               TEXT,
    AUSTRALIAN_CITIZEN_F               TEXT,
    AUSTRALIAN_CITIZEN_P               TEXT,
    AGE_PSNS_ATT_EDUC_INST_0_4_M       TEXT,
    AGE_PSNS_ATT_EDUC_INST_0_4_F       TEXT,
    AGE_PSNS_ATT_EDUC_INST_0_4_P       TEXT,
    AGE_PSNS_ATT_EDUC_INST_5_14_M      TEXT,
    AGE_PSNS_ATT_EDUC_INST_5_14_F      TEXT,
    AGE_PSNS_ATT_EDUC_INST_5_14_P      TEXT,
    AGE_PSNS_ATT_EDU_INST_15_19_M      TEXT,
    AGE_PSNS_ATT_EDU_INST_15_19_F      TEXT,
    AGE_PSNS_ATT_EDU_INST_15_19_P      TEXT,
    AGE_PSNS_ATT_EDU_INST_20_24_M      TEXT,
    AGE_PSNS_ATT_EDU_INST_20_24_F      TEXT,
    AGE_PSNS_ATT_EDU_INST_20_24_P      TEXT,
    AGE_PSNS_ATT_EDU_INST_25_OV_M      TEXT,
    AGE_PSNS_ATT_EDU_INST_25_OV_F      TEXT,
    AGE_PSNS_ATT_EDU_INST_25_OV_P      TEXT,
    HIGH_YR_SCHL_COMP_YR_12_EQ_M       TEXT,
    HIGH_YR_SCHL_COMP_YR_12_EQ_F       TEXT,
    HIGH_YR_SCHL_COMP_YR_12_EQ_P       TEXT,
    HIGH_YR_SCHL_COMP_YR_11_EQ_M       TEXT,
    HIGH_YR_SCHL_COMP_YR_11_EQ_F       TEXT,
    HIGH_YR_SCHL_COMP_YR_11_EQ_P       TEXT,
    HIGH_YR_SCHL_COMP_YR_10_EQ_M       TEXT,
    HIGH_YR_SCHL_COMP_YR_10_EQ_F       TEXT,
    HIGH_YR_SCHL_COMP_YR_10_EQ_P       TEXT,
    HIGH_YR_SCHL_COMP_YR_9_EQ_M        TEXT,
    HIGH_YR_SCHL_COMP_YR_9_EQ_F        TEXT,
    HIGH_YR_SCHL_COMP_YR_9_EQ_P        TEXT,
    HIGH_YR_SCHL_COMP_YR_8_BELW_M      TEXT,
    HIGH_YR_SCHL_COMP_YR_8_BELW_F      TEXT,
    HIGH_YR_SCHL_COMP_YR_8_BELW_P      TEXT,
    HIGH_YR_SCHL_COMP_D_N_G_SCH_M      TEXT,
    HIGH_YR_SCHL_COMP_D_N_G_SCH_F      TEXT,
    HIGH_YR_SCHL_COMP_D_N_G_SCH_P      TEXT,
    COUNT_PSNS_OCC_PRIV_DWGS_M         TEXT,
    COUNT_PSNS_OCC_PRIV_DWGS_F         TEXT,
    COUNT_PSNS_OCC_PRIV_DWGS_P         TEXT,
    COUNT_PERSONS_OTHER_DWGS_M         TEXT,
    COUNT_PERSONS_OTHER_DWGS_F         TEXT,
    COUNT_PERSONS_OTHER_DWGS_P         TEXT
);


CREATE TABLE BRONZE.CENSUS_DATA_G02_RAW (
    LGA_CODE_2016                     TEXT,
    MEDIAN_AGE_PERSONS                TEXT,
    MEDIAN_MORTGAGE_REPAY_MONTHLY     TEXT,
    MEDIAN_TOT_PRSNL_INC_WEEKLY       TEXT,
    MEDIAN_RENT_WEEKLY                TEXT,
    MEDIAN_TOT_FAM_INC_WEEKLY         TEXT,
    AVERAGE_NUM_PSNS_PER_BEDROOM      TEXT,
    MEDIAN_TOT_HHD_INC_WEEKLY         TEXT,
    AVERAGE_HOUSEHOLD_SIZE            TEXT
);

CREATE TABLE BRONZE.RAW_FACTS (
    LISTING_ID              TEXT, 
    SCRAPE_ID               TEXT,
    SCRAPED_DATE            TEXT,
    HOST_ID                 TEXT,
    HOST_NAME               TEXT,
    HOST_SINCE              TEXT,
    HOST_IS_SUPERHOST       TEXT,
    HOST_NEIGHBOURHOOD      TEXT,
    LISTING_NEIGHBOURHOOD   TEXT,
    PROPERTY_TYPE           TEXT,
    ROOM_TYPE               TEXT,
    ACCOMMODATES            TEXT,
    PRICE                   TEXT,
    HAS_AVAILABILITY        TEXT,
    AVAILABILITY_30         TEXT,
    NUMBER_OF_REVIEWS       TEXT,
    REVIEW_SCORES_RATING    TEXT,
    REVIEW_SCORES_ACCURACY  TEXT,
    REVIEW_SCORES_CLEANLINESS TEXT,
    REVIEW_SCORES_CHECKIN   TEXT,
    REVIEW_SCORES_COMMUNICATION TEXT,
    REVIEW_SCORES_VALUE     TEXT
);